/**
    Pathway Commons Central Data Cache

    Metadata Parser
    metadataParser.js

    Purpose  : To parse the subtree generated by the metadata parser
               into a human readable form

    Requires : Valid metadata subtree

    Effects  : Modifies the data structure of a node to be more human readable

    Note : Script may take time to parse metadata

    @author Harsh Mistry
    @version 1.1 2017/10/10
**/

//Returns all values mapped to a key in a given subtree 
//Requires subtree to be valid 
//Note : null is returned if no match is found
function searchTree(subtree, key){
  
}

function parse(subTree){
}